sudo: required
dist: precise
language: cpp

notifications:
  email: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - debian-sid
          packages:
            - g++-4.9
            - libnlopt-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - debian-sid
          packages:
            - g++-5
            - libnlopt-dev
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - debian-sid
          packages:
            - clang-3.6
            - libnlopt-dev
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - debian-sid
          packages:
            - clang-3.7
            - libnlopt-dev
      env: COMPILER=clang++-3.7

script:
  - make CXX=$COMPILER devel test
